#-----------------------------------------------------------------------
# Hugo config for FirstCondo.ca
#-----------------------------------------------------------------------
baseURL = "https://www.firstcondo.ca/"
title = "FirstCondo"

theme = "fcg-2024"
disablePathToLower = true  # Original website had mixed case URLs
enableRobotsTXT = false
#defaultContentLanguage = "en"
#defaultContentLanguageInSubdir = true
#enableMissingTranslationPlaceholders = false

[params]
  theme_colour = "#387c2c"

[taxonomies]  # Disable the default taxonomies
tag = ""
category = ""

[markup.tableOfContents]
  startLevel = 1
  endLevel = 4
  ordered = false
[markup.highlight]
  lineNos = true
  lineNumbersInTable = false
  style = 'witchhazel'
[markup.goldmark.parser.attribute]
  block = true
[markup.goldmark.renderer]
  unsafe = true
