[hugoVersion]
    extended = true
    #max = ''
    #min = ''

[[mounts]]
    source = '../content'
    target = 'content'
[[mounts]]
    source = '../data'
    target = 'data'
[[mounts]]
    source = 'static'
    target = 'static'
[[mounts]]
    source = 'layouts'
    target = 'layouts'
[[mounts]]
    source = 'assets'
    target = 'assets'
[[mounts]]
    source = 'i18n'
    target = 'i18n'
[[mounts]]
    source = 'archetypes'
    target = 'archetypes'
